#include "Cell.h"

Cell::Cell()
    : epsilon_(0.),
      g2mu2A_(0.),
      TpA_(0.),
      g2mu2B_(0.),
      TpB_(0.),
      Ttautau_(0.),
      Txx_(0.),
      Tyy_(0.),
      Txy_(0.),
      Tetaeta_(0.),
      Ttaux_(0.),
      Ttauy_(0.),
      Ttaueta_(0.),
      Txeta_(0.),
      Tyeta_(0.),
      pitautau_(0.),
      pixx_(0.),
      piyy_(0.),
      pixy_(0.),
      pietaeta_(0.),
      pitaux_(0.),
      pitauy_(0.),
      pitaueta_(0.),
      pixeta_(0.),
      piyeta_(0.),
      utau_(0.),
      ux_(0.),
      uy_(0.),
      ueta_(0.) {}
