#ifndef SRC_LATTICE_H_
#define SRC_LATTICE_H_

#include <string>
#include <vector>

#include "Cell.h"
#include "Matrix.h"
#include "Parameters.h"
#include "PrettyOstream.h"

enum class NucleusRole;

// Lattice matrix state is stored structure-of-arrays: every fundamental SU(3)
// field is one contiguous std::vector<Matrix>, and Matrix itself is exactly
// complex<double>[9]. Cell now contains scalar observables only; matrix hot
// paths access these field arrays directly, without Cell pointer chasing.
class Lattice {
  private:
    int size_;
    static constexpr int Nc_ = 3;
    PrettyOstream messager_;

    // Shared by writeSU3Matrices()'s Phi and Pi passes: writes one N*N
    // Matrix array to a text file in "ix iy MatrixToString()" format.
    void writeMatrixArrayText(
        const std::string &file_name, std::vector<Matrix> &field, int N);

  public:
    Lattice(Parameters *param, int length);
    ~Lattice() = default;
    Lattice(const Lattice &) = delete;
    Lattice &operator=(const Lattice &) = delete;

    int getSize() const { return size_; }

    // Fundamental matrix lattice fields. Logical aliases are:
    // U/E1, U2/E2, Ux1/g, Uy1/Uplaq, Ux2/pi, Uy2/phi.
    std::vector<Matrix> U;
    std::vector<Matrix> U2;
    std::vector<Matrix> Ux;
    std::vector<Matrix> Uy;
    std::vector<Matrix> Ux1;
    std::vector<Matrix> Uy1;
    std::vector<Matrix> Ux2;
    std::vector<Matrix> Uy2;

    std::vector<Cell *> cells;
    std::vector<Cell> cellStorage;

    std::vector<int> posmX;
    std::vector<int> pospX;
    std::vector<int> posmY;
    std::vector<int> pospY;

    /*
     * Write Wilson lines to disk in either text or binary format, depending on
     * the value of param->getWriteWilsonLines(). The output filename is
     * generated by generateWilsonLineDataFile() If the optional argumet x is
     * provided, the generated filename includes x in the filename, otherwise it
     * does not.
     */
    void writeWilsonLines(
        Parameters *param, NucleusRole nucleus, double x = -1);
    void writeSU3Matrices(std::string fileprefix, Parameters *param);
    std::vector<int> posmXpY;
    std::vector<int> pospXmY;

    /*
     * Check if the given Wilson line data format value is valid.
     * The valid values are 1 (text) and 2 (binary).
     * WriteWilsonLines() determines the output format based on
     * param->getWriteWilsonLines()
     */
    static bool IsValidWilsonLineDataFormat(const int format) {
        return format == 1 || format == 2;
    }

    /*
     * Generate filename for Wilson lines stored on disc
     */
    static std::string generateWilsonLineDataFileName(
        Parameters *param, const double x, NucleusRole nucleus);
};

class BufferLattice {
  private:
    int size_;

  public:
    explicit BufferLattice(int length);
    ~BufferLattice() = default;
    BufferLattice(const BufferLattice &) = delete;
    BufferLattice &operator=(const BufferLattice &) = delete;

    std::vector<Matrix> buffer1;
    std::vector<Matrix> buffer2;
};

#endif  // SRC_LATTICE_H_
