// WilsonLineIO.h is part of the IP-Glasma solver.

#ifndef SRC_WILSONLINEIO_H_
#define SRC_WILSONLINEIO_H_

#include <string>
#include <vector>

#include "Glauber.h"
#include "Lattice.h"
#include "Matrix.h"
#include "Parameters.h"
#include "PrettyOstream.h"

/**
 * Writing and reading the projectile's and target's Wilson lines
 * (lat->U / lat->U2), in the text (`1`) or binary (`2`) format selected
 * by `writeWilsonLines` / `readInitialWilsonLines`.
 * The writer and the matching reader live together here, so that the
 * file layout is defined in one place.
 */
class WilsonLineIO {
  public:
    /**
     * Checks whether a `writeWilsonLines`/`readInitialWilsonLines`
     * input value is one of the formats write() actually
     * supports.
     * \param[in] format Value to check.
     * \return `true` if \p format is `1` (text) or `2` (binary).
     */
    static bool isValidFormat(const int format) {
        return format == 1 || format == 2;
    }
    /**
     * Generates the deterministic file name write() writes to
     * (and WilsonLineIO::read() reads from): `<wilsonLines.wilsonLinePath>/
     * WilsonLine[_x_<x>]_<event/nucleus/seed/rank-derived index>[.txt]`.
     * \param[in] param Simulation parameters;
     * `param->wilsonLines.wilsonLinePath`, `param->event.eventId`,
     * `param->random.seed`, `param->run.MPISize` and (when \p format is
     * negative) `param->wilsonLines.writeWilsonLines` are used.
     * \param[in] x If non-negative, embedded in the file name
     * (`_x_<x>`, in scientific notation); a negative value omits it.
     * \param[in] nucleus Which nucleus this file belongs to (offsets
     * the numeric index so the projectile and target never collide).
     * \param[in] format Overrides `param->wilsonLines.writeWilsonLines` for
     * deciding whether to append the `.txt` extension (`1`: text,
     * anything else: binary, no extension); a negative value (the
     * default) uses `param->wilsonLines.writeWilsonLines` instead.
     * \return The generated file path.
     */
    static std::string fileName(
        Parameters *param, const double x, NucleusRole nucleus,
        int format = -1);
    /**
     * Writes the projectile's or target's Wilson line
     * (\c lat->U or \c lat->U2) to disk, in text or binary format depending on
     * \p param's `param->wilsonLines.writeWilsonLines`. The output file name is
     * generated by fileName().
     * The file is described in \ref md_OUTPUT "OUTPUT.md".
     * \param[in] lat Lattice holding the Wilson lines.
     * \param[in] param Simulation parameters; `param->lattice.size`,
     * `param->lattice.L`, `param->event.eventId`, `param->random.seed`,
     * `param->run.MPISize`, `param->wilsonLines.wilsonLinePath`,
     * `param->wilsonLines.writeWilsonLines` and (binary format only)
     * `param->colorCharge.rapidityA`/`param->colorCharge.rapidityB` are used.
     * \param[in] nucleus Which of \c U (Projectile) / \c U2 (Target) to
     * write.
     * \param[in] x If non-negative, included in the generated file name
     * (see fileName()); the default `-1` omits it.
     *
     * Format `1` (text): one line per site, `ix iy
     * MatrixToString()`. Format `2` (binary): a
     * `{N, Nc, L, a, rapidity}` header followed by every site's 9
     * complex components as consecutive `{real, imag}` `double` pairs,
     * indexed `N*ix+iy` (matching every other `U`/`U2` indexing in
     * the codebase; see WilsonLineIO::read for the matching reader).
     * Exits with an error for any other `param->wilsonLines.writeWilsonLines`
     * value, or if the binary write fails.
     */
    void write(
        Lattice *lat, Parameters *param, NucleusRole nucleus, double x = -1);
    /**
     * Reads both nuclei's Wilson lines from disk, using
     * fileName() to build each file
     * name, in text or binary format depending on \p format.
     * \param[in,out] lat Lattice whose `U`/`U2` are set.
     * \param[in] param Simulation parameters.
     * \param[in] format `1` for plain text, `2` for binary; exits with
     * an error for any other value
     * (`isValidFormat()`).
     * \param[in] x If non-negative, embedded in the generated file
     * names (see fileName()); the
     * default `-1` omits it, matching a file written without an
     * explicit \f$x\f$ (e.g. by Init::setV() outside JIMWLK/fluctuating-
     * \f$x\f$ runs).
     */
    void read(Lattice *lat, Parameters *param, int format, double x = -1);
    /**
     * read()'s `format==1` branch: reads one nucleus' Wilson
     * line from a plain-text file, shifting it by \f$\mp b/2\f$ along
     * the impact-parameter direction and dropping any resulting
     * out-of-bounds column (on the low side for the projectile, the
     * high side for the target).
     * \param[in] fileName Path to read from; exits with an error if it
     * doesn't exist.
     * \param[in] param Simulation parameters.
     * \param[in] role Which nucleus this file belongs to (selects the
     * sign of the \f$b/2\f$ shift and which side out-of-bounds columns
     * are dropped on).
     * \param[out] U Wilson-line field to fill (`lat->U` or `lat->U2`).
     */
    void readText(
        const std::string &fileName, Parameters *param, NucleusRole role,
        std::vector<Matrix> &U);
    /**
     * read()'s `format==2` branch: reads one nucleus' Wilson
     * line from a binary file (the format write()'s
     * binary mode writes), shifting it by \f$\mp b/2\f$ along the
     * impact-parameter direction.
     * \param[in] fileName Path to read from; exits with an error if it
     * doesn't exist, or if the file's lattice size/physical length
     * don't match \p param.
     * \param[in] param Simulation parameters.
     * \param[in] role Which nucleus this file belongs to (selects the
     * sign of the \f$b/2\f$ shift).
     * \param[out] U Wilson-line field to fill (`lat->U` or `lat->U2`).
     */
    void readBinary(
        const std::string &fileName, Parameters *param, NucleusRole role,
        std::vector<Matrix> &U);
    /**
     * The `writeOutputs==5` diagnostic of Init::setV(): writes
     * `initialWilsonLines<id>.ipgw`, a binary snapshot of the two nuclei's
     * just-constructed initial Wilson lines (\c lat->U/\c lat->U2) as full
     * \f$3\times3\f$ complex matrices per cell, little-endian
     * single-precision, preceded by an 8-byte magic string, an 8-byte
     * metadata length, and a JSON metadata header describing the
     * layout/units -- the same format convention as
     * Evolution::writeEvolvedFields().
     * The file is described in \ref md_OUTPUT "OUTPUT.md".
     * \param[in] lat Lattice to read `U`/`U2` from.
     * \param[in] param Simulation parameters.
     */
    void writeTrainingData(Lattice *lat, Parameters *param);

  private:
    /// Log sink for progress/error messages.
    PrettyOstream messager_;
};

#endif  // SRC_WILSONLINEIO_H_
