// WilsonLineIO.h is part of the IP-Glasma solver.

#ifndef SRC_WILSONLINEIO_H_
#define SRC_WILSONLINEIO_H_

#include <string>
#include <vector>

#include "Glauber.h"
#include "Lattice.h"
#include "Matrix.h"
#include "Parameters.h"
#include "PrettyOstream.h"

/**
 * The nucleons and the color-charge and thickness maps of one nucleus,
 * as stored next to its Wilson lines, see WilsonLineIO::readGeometry().
 */
struct NucleusGeometry {
    /// The nucleons, centered at the origin.
    std::vector<ReturnValue> nucleons;
    /// \f$Q_s/(g^2\mu)\f$ the color-charge map was built with.
    double QsMuRatio = 0.;
};

/**
 * Writing and reading the projectile's and target's Wilson lines
 * (lat->U / lat->U2), in the text (`1`) or binary (`2`) format selected
 * by `writeWilsonLines` / `readInitialWilsonLines`.
 * The writer and the matching reader live together here, so that the
 * file layout is defined in one place.
 */
class WilsonLineIO {
  public:
    /**
     * Checks whether a `writeWilsonLines`/`readInitialWilsonLines`
     * input value is one of the formats write() actually
     * supports.
     * \param[in] format Value to check.
     * \return `true` if \p format is `1` (text) or `2` (binary).
     */
    static bool isValidFormat(const int format) {
        return format == 1 || format == 2;
    }
    /**
     * Generates the deterministic file name write() writes to
     * (and WilsonLineIO::read() reads from): `<wilsonLines.wilsonLinePath>/
     * WilsonLine[_x_<x>]_<n>[.txt]` with \f$n = 2(sN + i) + j\f$, where
     * \f$s\f$ is the seed, \f$N\f$ the number of events of the run (events
     * per rank times ranks), \f$i\f$ the event id and \f$j\f$ `1` for the
     * projectile and `2` for the target. So every nucleus and event of a run,
     * and runs with different seeds and the same \f$N\f$, get different
     * names.
     * \param[in] param Simulation parameters;
     * `param->wilsonLines.wilsonLinePath`, `param->event.eventId`,
     * `param->random.seed`, `param->run.MPISize`,
     * `param->run.eventsPerRank` and (when \p format is negative)
     * `param->wilsonLines.writeWilsonLines` are used.
     * \param[in] x If non-negative, embedded in the file name
     * (`_x_<x>`, in scientific notation); a negative value omits it.
     * \param[in] nucleus Which nucleus this file belongs to.
     * \param[in] format Overrides `param->wilsonLines.writeWilsonLines` for
     * deciding whether to append the `.txt` extension (`1`: text,
     * anything else: binary, no extension); a negative value (the
     * default) uses `param->wilsonLines.writeWilsonLines` instead.
     * \return The generated file path.
     */
    static std::string fileName(
        Parameters *param, const double x, NucleusRole nucleus,
        int format = -1);
    /**
     * Writes the projectile's or target's Wilson line
     * (\c lat->U or \c lat->U2) to disk, in text or binary format depending on
     * \p param's `param->wilsonLines.writeWilsonLines`. The output file name is
     * generated by fileName().
     * The file is described in \ref md_OUTPUT "OUTPUT.md".
     * \param[in] lat Lattice holding the Wilson lines.
     * \param[in] param Simulation parameters; `param->lattice.size`,
     * `param->lattice.L`, `param->event.eventId`, `param->random.seed`,
     * `param->run.MPISize`, `param->run.eventsPerRank`,
     * `param->wilsonLines.wilsonLinePath`,
     * `param->wilsonLines.writeWilsonLines` and (binary format only)
     * `param->colorCharge.rapidityA`/`param->colorCharge.rapidityB` are used.
     * \param[in] nucleus Which of \c U (Projectile) / \c U2 (Target) to
     * write.
     * \param[in] x If non-negative, included in the generated file name
     * (see fileName()); the default `-1` omits it.
     *
     * Format `1` (text): one line per site, `ix iy
     * MatrixToString()`. Format `2` (binary): a
     * `{N, Nc, L, a, rapidity}` header followed by every site's 9
     * complex components as consecutive `{real, imag}` `double` pairs,
     * indexed `N*ix+iy` (matching every other `U`/`U2` indexing in
     * the codebase; see WilsonLineIO::read for the matching reader).
     * Exits with an error for any other `param->wilsonLines.writeWilsonLines`
     * value, or if the binary write fails.
     */
    void write(
        Lattice *lat, Parameters *param, NucleusRole nucleus, double x = -1);
    /**
     * The \f$x\f$ in the names of a nucleus' initial Wilson-line files,
     * which Init::setV() writes and read() reads: `jimwlkInitialX` with
     * JIMWLK, none (`-1`) with `useFluctuatingX 1`, and otherwise
     * \f$0.01\,e^{-y}\f$ with \f$y\f$ = `rapidityA` or `rapidityB`.
     * \param[in] param Simulation parameters.
     * \param[in] nucleus Which nucleus.
     * \return The \f$x\f$, or `-1` for none.
     */
    static double initialX(Parameters *param, NucleusRole nucleus);
    /**
     * The \f$x\f$ in the names of the Wilson-line files read():
     * `readWilsonLinesX` if it is set (positive), otherwise initialX().
     * \param[in] param Simulation parameters.
     * \param[in] nucleus Which nucleus.
     * \return The \f$x\f$, or `-1` for none.
     */
    static double xToRead(Parameters *param, NucleusRole nucleus);
    /**
     * Generates the name of a nucleus' geometry file, which
     * writeGeometry() writes and readGeometry() reads:
     * `<wilsonLines.wilsonLinePath>/WilsonLineGeometry_<n>`, with the same
     * number \f$n\f$ as the nucleus' Wilson-line files (fileName()) and no
     * \f$x\f$, since one geometry serves the Wilson lines at every
     * \f$x\f$.
     * \param[in] param Simulation parameters.
     * \param[in] nucleus Which nucleus.
     * \return The generated file path.
     */
    static std::string geometryFileName(Parameters *param, NucleusRole nucleus);
    /**
     * Writes a nucleus' geometry file (geometryFileName()), which
     * readGeometry() needs to collide the nucleus' Wilson lines like
     * sampled ones: its nucleons and its \f$g^2\mu^2\f$ and \f$T_p\f$ maps
     * as little-endian doubles, preceded by an 8-byte magic string, an
     * 8-byte metadata length and a JSON metadata header.
     * The file is described in \ref md_OUTPUT "OUTPUT.md".
     * \param[in] lat Lattice to read the color-charge densities
     * (`g2mu2A`/`g2mu2B`) and thicknesses (`TpA`/`TpB`) from.
     * \param[in] param Simulation parameters.
     * \param[in] nucleus Which nucleus.
     * \param[in] nucleons The nucleus' nucleons, centered at the origin.
     */
    void writeGeometry(
        Lattice *lat, Parameters *param, NucleusRole nucleus,
        const std::vector<ReturnValue> &nucleons);
    /**
     * Reads a nucleus' geometry file (geometryFileName()), sets its
     * \f$g^2\mu^2\f$ and \f$T_p\f$ maps on \p lat and returns its nucleons.
     * Exits with an error if the file is missing or belongs to another
     * nucleus, species, lattice or \f$g\f$.
     * \param[in,out] lat Lattice whose `g2mu2A`/`TpA` (projectile) or
     * `g2mu2B`/`TpB` (target) are set.
     * \param[in] param Simulation parameters.
     * \param[in] nucleus Which nucleus.
     * \return The nucleons and the \f$Q_s/(g^2\mu)\f$ ratio the file was
     * written with.
     */
    NucleusGeometry readGeometry(
        Lattice *lat, Parameters *param, NucleusRole nucleus);
    /**
     * Reads both nuclei's Wilson lines from disk, from the files a run
     * with the same parameters writes (fileName() with xToRead()), in text
     * or binary format depending on \p format. The fields are placed as
     * written, centered at the origin; the impact parameter is applied
     * later, by Init::shiftFieldsWithImpactParameter().
     * \param[in,out] lat Lattice whose `U`/`U2` are set.
     * \param[in] param Simulation parameters.
     * \param[in] format `1` for plain text, `2` for binary; exits with
     * an error for any other value
     * (`isValidFormat()`).
     */
    void read(Lattice *lat, Parameters *param, int format);
    /**
     * read()'s `format==1` branch: reads one nucleus' Wilson line from a
     * plain-text file, site by site in the order write() writes them.
     * \param[in] fileName Path to read from; exits with an error if it
     * doesn't exist.
     * \param[in] param Simulation parameters.
     * \param[out] U Wilson-line field to fill (`lat->U` or `lat->U2`).
     */
    void readText(
        const std::string &fileName, Parameters *param, std::vector<Matrix> &U);
    /**
     * read()'s `format==2` branch: reads one nucleus' Wilson line from a
     * binary file (the format write()'s binary mode writes).
     * \param[in] fileName Path to read from; exits with an error if it
     * doesn't exist, or if the file's lattice size/physical length
     * don't match \p param.
     * \param[in] param Simulation parameters.
     * \param[out] U Wilson-line field to fill (`lat->U` or `lat->U2`).
     */
    void readBinary(
        const std::string &fileName, Parameters *param, std::vector<Matrix> &U);
    /**
     * The `writeWilsonLineSnapshot` diagnostic of Init::setV(): writes
     * `initialWilsonLines<id>.ipgw`, a binary snapshot of the two nuclei's
     * just-constructed initial Wilson lines (\c lat->U/\c lat->U2) as full
     * \f$3\times3\f$ complex matrices per cell, little-endian
     * single-precision, preceded by an 8-byte magic string, an 8-byte
     * metadata length, and a JSON metadata header describing the
     * layout/units -- the same format convention as
     * Evolution::writeEvolvedFields().
     * The file is described in \ref md_OUTPUT "OUTPUT.md".
     * \param[in] lat Lattice to read `U`/`U2` from.
     * \param[in] param Simulation parameters.
     */
    void writeTrainingData(Lattice *lat, Parameters *param);

  private:
    /// Log sink for progress/error messages.
    PrettyOstream messager_;
};

#endif  // SRC_WILSONLINEIO_H_
